netty:
  port: 12307
  host: 127.0.0.1


# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  servlet:
    context-path: /jike-api

# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: a1519877813
    virtual-host: /



logging:
  level:
    me.cocode.jike.dao: debug
